# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopOnGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopOnGo

  target 'ShopOnGoTests' do
    inherit! :search_paths
    # Pods for testing
pod 'KYDrawerController'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'SwiftyJSON'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'DateTimePicker', '~>1.1.4'
pod 'FirebaseInstanceID', '2.0.0'
pod 'WalmartOpenApi'
  end

  target 'ShopOnGoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


